steps:
  - name: ":rspec:"
    command: "scripts/ci/parallel_specs.sh"
    artifact_paths: "log/**/*"
    env:
      RAILS_ENV: test
    plugins:
      - docker-compose#v3.9.0:
          run: app
      - kubernetes:
          podSpec:
            containers:
            - name: compose
              image: buildkite/agent:latest
              volumeMounts:
              - name: dind
                mountPath: /var/run/
            volumes:
            - name: dind
              hostPath:
                path: /var/run/dind/
    parallelism: 20
    agents:
      queue: $BUILDKITE_AGENT_META_DATA_QUEUE
