steps:
  - name: ":rspec:"
    artifact_paths: "log/**/*"
    env:
      RAILS_ENV: test
    plugins:
      - docker-compose#v3.9.0:
          run: app
      - kubernetes:
          podSpec:
            containers:
            - name: compose
              command: [scripts/ci/parallel_specs.sh]
              image: buildkite/agent:latest
              env:
                - name: DOCKER_HOST
                  value: tcp://docker:2375
    parallelism: 20
    agents:
      queue: $BUILDKITE_AGENT_META_DATA_QUEUE
