steps:
  - label: ":docker: Build"
    plugins:
      - docker-compose#v4.9.0:
          build: app
          image-repository: kind-registry:5000/rails
      - kubernetes:
          sidecars:
          - name: dind
            image: docker:dind
            securityContext:
              privileged: true
          podSpec:
            containers:
            - name: build
              image: buildkite/agent:latest
    agents:
      queue: $BUILDKITE_AGENT_META_DATA_QUEUE
  - wait
  - name: ":rspec:"
    artifact_paths: "log/**/*"
    env:
      RAILS_ENV: test
      BUILDKITE_PLUGIN_DOCKER_COMPOSE_REQUIRE_PREBUILD: true
    plugins:
      - docker-compose#v3.9.0:
          run: app
      - kubernetes:
          sidecars:
          - name: dind
            image: docker:dind
            securityContext:
              privileged: true
          podSpec:
            containers:
            - name: compose
              command: [scripts/ci/parallel_specs.sh]
              image: buildkite/agent:latest
              env:
                - name: DOCKER_HOST
                  value: tcp://docker:2375
    parallelism: 5
    agents:
      queue: $BUILDKITE_AGENT_META_DATA_QUEUE
